version: "3.8"
services:
    backendService:
        container_name: backendService
        volumes:
            -   ./:/app
        ports:
            - "8889:8889"
        image: node:slim
        command: bash -c "cd /app && npm install && npm run start"

networks:
    be-network:
        driver: host

volumes:
    be-database:
        driver: local
